modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "cobbled_counter"
version = "1.6-neoforge-1.3.5"
displayName = "Cobblemon Counter"
authors = "timinc aka Timothy Metcalfe"
description = '''
Counts things in Cobblemon
'''

[[dependencies.cobbled_counter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbled_counter]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbled_counter]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,1.7.0)"
ordering = "AFTER"
side = "BOTH"
